### ISSUE TITLE
LimitDistance in OTCDealConfirmation is wrong type. should be float64, is string. causes error.

### ISSUE THREAD

**Issue by wiqram** [sklinkert/igmarkets#4]
LimitDistance attribute in OTCDealConfirmation is wrong type. should be float64, is string. causes error.

**Comment by sklinkert** [comment]
Hi @wiqram! Thanks for reporting it. Should be fixed by https://github.com/sklinkert/igmarkets/commit/5d3af4ae54fa0b563d909dbbf0e39f8f17f2f696 now.

**Comment by wiqram** [comment]
Thanks for fixing it @sklinkert . One More fix for a bug, please.

Can you send a response with deal confirmation for the below function in igmarkets - just replace your function with below.

// DeleteOTCWorkingOrder - Delete workingorder
func (ig *IGMarkets) DeleteOTCWorkingOrder(dealRef string) (*DealReference, error) {
	bodyReq := new(bytes.Buffer)

	req, err := http.NewRequest("DELETE", ig.APIURL+"/gateway/deal/workingorders/otc/"+dealRef, bodyReq)
	if err != nil {
		return nil, fmt.Errorf("igmarkets: unable to create HTTP request: %v", err)
	}

	igResponseInterface, err := ig.doRequest(req, 2, DealReference{})
	if err != nil {
		return nil, err
	}
	return igResponseInterface.(*DealReference), nil
}

**Comment by sklinkert** [comment]
@wiqram Sure, should be fixed in https://github.com/sklinkert/igmarkets/commit/8e38e3992fd44a23faa1b57c396af378fab5dcf3.
